pypi-publish:
  runs-on: ubuntu-latest
  needs: release-build
  permissions:
    id-token: write  # Needed for trusted publishing

  environment:
    name: pypi

  steps:
    - name: Retrieve release distributions
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Publish to PyPI (with Trusted Publisher)
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        attestations: true  # Enable attestations for trusted publishing
